### ISSUE TITLE
During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "D:\TGbot\DuckChainBot\venv\lib\site-packages\pyrogram\client.py", line 569, in handle_updates     channel=await self.resolve_peer(utils.get_channel_id(channel_id)),   File "D:\TGbot\DuckChainBot\venv\lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 89, in resolve_peer     peer_type = utils.get_peer_type(peer_id)   File "D:\TGbot\DuckChainBot\venv\lib\site-packages\pyrogram\utils.py", line 246, in get_peer_type     raise ValueError(f"Peer id invalid: {peer_id}") ValueError: Peer id invalid: -1002185840052

### ISSUE THREAD

**Issue by 1573712107** [SkalaFrost/DuckChainBot#6]
help

**Comment by SkalaFrost** [comment]
fixed, dm me (tg) if still getting errorw
